"""Product definitions for Blizzard CDN product codes.

Product codes sourced from Blizzard's Ribbit service listing.
"""

import re
from enum import Enum
from typing import Dict, List, Optional


# All known product codes from Blizzard's Ribbit service.
# Sorted alphabetically. Legacy codes not in current Ribbit listing
# are included for backward compatibility.
ALL_PRODUCT_CODES = (
    "agent",
    "agent_beta",
    "agent_redist",
    "anbs",
    "anbs-event",
    "anbs-retail-dev-1",
    "anbs-retail-rc",
    "anbscn",
    "anbsdev",
    "anbsdev2",
    "aqua",
    "aqua-artbook",
    "aqua-artbook-dev-1",
    "aqua-artbook-rc",
    "aqua-retail-dev-1",
    "aqua-retail-rc",
    "aris",
    "aris-artbook",
    "aris-artbook-dev-1",
    "aris-artbook-rc",
    "aris-retail-dev-1",
    "aris-retail-rc",
    "ark",
    "ark-artbook",
    "ark-artbook-dev-1",
    "ark-artbook-rc",
    "ark-retail-dev-1",
    "ark-retail-rc",
    "auks",
    "auks123",
    "auksa",
    "auksb",
    "auksdev",
    "aukse",
    "aukse2",
    "auksese",
    "auksesp",
    "auksess",
    "auksrc",
    "auksrc2",
    "aukst",
    "auksv1",
    "auksv10",
    "auksv11",
    "auksv12",
    "auksv13",
    "auksv14",
    "auksv15",
    "auksv16",
    "auksv17",
    "auksv18",
    "auksv19",
    "auksv2",
    "auksv20",
    "auksv21",
    "auksv22",
    "auksv23",
    "auksv3",
    "auksv4",
    "auksv5",
    "auksv6",
    "auksv7",
    "auksv8",
    "auksv9",
    "bdko-retail-dev-1",
    "bna",
    "brynhildr_odin",
    "brynhildr_odin_qa",
    "brynhildr_odin_qa2",
    "brynhildr_odin_vendor",
    "brynhildr_odin_vendor2",
    "brynhildr_odin2",
    "btlrv1",
    "btlrv10",
    "btlrv11",
    "btlrv12",
    "btlrv13",
    "btlrv14",
    "btlrv15",
    "btlrv16",
    "btlrv17",
    "btlrv18",
    "btlrv19",
    "btlrv2",
    "btlrv20",
    "btlrv21",
    "btlrv22",
    "btlrv23",
    "btlrv24",
    "btlrv25",
    "btlrv26",
    "btlrv27",
    "btlrv28",
    "btlrv29",
    "btlrv3",
    "btlrv30",
    "btlrv4",
    "btlrv5",
    "btlrv6",
    "btlrv7",
    "btlrv8",
    "btlrv9",
    "bts",
    "catalogs",
    "cornv1",
    "cornv10",
    "cornv11",
    "cornv12",
    "cornv13",
    "cornv14",
    "cornv15",
    "cornv16",
    "cornv17",
    "cornv18",
    "cornv19",
    "cornv2",
    "cornv20",
    "cornv21",
    "cornv22",
    "cornv23",
    "cornv24",
    "cornv25",
    "cornv26",
    "cornv27",
    "cornv28",
    "cornv29",
    "cornv3",
    "cornv30",
    "cornv4",
    "cornv5",
    "cornv6",
    "cornv7",
    "cornv8",
    "cornv9",
    "d3",
    "d3cn",
    "d3t",
    "d3vcn",
    "drtl",
    "drtl2",
    "fenris",
    "fenrisb",
    "fenrisdev",
    "fenrisdev2",
    "fenrise",
    "fenrise2",
    "fenrishf",
    "fenristest",
    "fenrisvendor",
    "fenrisvendor10",
    "fenrisvendor2",
    "fenrisvendor3",
    "fenrisvendor4",
    "fenrisvendor5",
    "fenrisvendor6",
    "fenrisvendor7",
    "fenrisvendor8",
    "fenrisvendor9",
    "fore",
    "forea",
    "foreb",
    "forec",
    "forecdlstaff",
    "foredev",
    "forev1",
    "forev10",
    "forev11",
    "forev12",
    "forev13",
    "forev14",
    "forev15",
    "forev16",
    "forev17",
    "forev18",
    "forev19",
    "forev2",
    "forev20",
    "forev3",
    "forev4",
    "forev5",
    "forev6",
    "forev7",
    "forev8",
    "forev9",
    "gdt",
    "gdt-retail-dev-1",
    "gdt-retail-dev-2",
    "gdt-retail-rc",
    "geirdrifulfore",
    "geirdrifulforecdl",
    "geirdrifulforecdlqa",
    "geirdrifulforecdls",
    "geirdrifulforecdlv",
    "geirdrifulforeqa",
    "geirdrifulforev",
    "gryphon",
    "gryphondev",
    "gryphondev3",
    "gryphonv",
    "hero",
    "heroc",
    "herot",
    "hristnina",
    "hristninaav",
    "hristninaav2",
    "hristninaqa",
    "hristninaqa2",
    "hsb",
    "hsc",
    "hsdev",
    "hse",
    "hse1",
    "hsrc",
    "lazr",
    "lazrv1",
    "lazrv2",
    "lbra",
    "lbra-demo",
    "lbra-demo-dev-1",
    "lbra-demo-rc",
    "lbra-retail-dev-1",
    "lbra-retail-rc",
    "lbra-test-dev-1",
    "lbra-test-rc",
    "moonv1",
    "moonv10",
    "moonv11",
    "moonv12",
    "moonv13",
    "moonv14",
    "moonv15",
    "moonv16",
    "moonv17",
    "moonv18",
    "moonv19",
    "moonv2",
    "moonv20",
    "moonv21",
    "moonv22",
    "moonv23",
    "moonv24",
    "moonv25",
    "moonv26",
    "moonv27",
    "moonv28",
    "moonv3",
    "moonv4",
    "moonv5",
    "moonv6",
    "moonv7",
    "moonv8",
    "moonv9",
    "nina",
    "ninav1",
    "ninav2",
    "ninav3",
    "ninav4",
    "ninav5",
    "odin",
    "odina",
    "odinb",
    "odindev",
    "odine",
    "odinv1",
    "odinv10",
    "odinv11",
    "odinv12",
    "odinv13",
    "odinv14",
    "odinv15",
    "odinv16",
    "odinv2",
    "odinv3",
    "odinv4",
    "odinv5",
    "odinv6",
    "odinv7",
    "odinv8",
    "odinv9",
    "orbisdev",
    "osi",
    "osia",
    "osib",
    "osic",
    "osidev",
    "osit",
    "osiv1",
    "osiv2",
    "osiv3",
    "osiv4",
    "osiv5",
    "osiv6",
    "osiv7",
    "pinta",
    "pro",
    "prob",
    "probv1",
    "probv2",
    "probv3",
    "proc",
    "proc_cn",
    "proc_eu",
    "proc_kr",
    "proc2",
    "proc2_cn",
    "proc2_eu",
    "proc2_kr",
    "proc3",
    "proc4",
    "proc5",
    "procr",
    "procr2",
    "prodemo",
    "prodemo2",
    "prodemo3",
    "prodemo4",
    "prodemo5",
    "prodev",
    "prodev10",
    "prodev11",
    "prodev12",
    "prodev13",
    "prodev14",
    "prodev6",
    "prodev7",
    "prodev8",
    "prodev9",
    "prodevops",
    "prodevops2",
    "proev",
    "proindev",
    "prolocv1",
    "prolocv2",
    "prolocv3",
    "prolocv4",
    "proms",
    "prot",
    "proutr",
    "prov",
    "provac",
    "provbv",
    "provcomp",
    "providcn1",
    "providcn2",
    "providcn3",
    "randgridauks",
    "randgridauks2",
    "randgridaukscdl",
    "randgridaukscdlqa",
    "randgridaukscdls",
    "randgridaukscdlv",
    "randgridaukse",
    "randgridaukslivedev",
    "randgridauksqa",
    "randgridauksqa2",
    "randgridauksrc",
    "randgridauksrc2",
    "randgridauksv",
    "randgridauksv2",
    "randgridbtlraqa",
    "randgridbtlraqa2",
    "randgridbtlrav",
    "randgridbtlrav2",
    "randgridbtlrbcdlqa",
    "randgridbtlrbcdlv",
    "randgridbtlrbqa",
    "randgridbtlrbqa2",
    "randgridbtlrbv",
    "randgridbtlrbv2",
    "randgridcornaqa",
    "randgridcornaqa2",
    "randgridcornav",
    "randgridcornav2",
    "randgridcornbcdlqa",
    "randgridcornbcdlv",
    "randgridcornbqa",
    "randgridcornbqa2",
    "randgridcornbv",
    "randgridcornbv2",
    "randgridmoonaqa",
    "randgridmoonaqa2",
    "randgridmoonav",
    "randgridmoonav2",
    "randgridmoonbcdlqa",
    "randgridmoonbcdlv",
    "randgridmoonbqa",
    "randgridmoonbqa2",
    "randgridmoonbv",
    "randgridmoonbv2",
    "randgridroseaqa",
    "randgridroseaqa2",
    "randgridroseav",
    "randgridroseav2",
    "randgridrosebcdlqa",
    "randgridrosebcdlv",
    "randgridrosebqa",
    "randgridrosebqa2",
    "randgridrosebv",
    "randgridrosebv2",
    "randgridsageaqa",
    "randgridsageaqa2",
    "randgridsageav",
    "randgridsageav2",
    "randgridsagebcdlqa",
    "randgridsagebcdlv",
    "randgridsagebqa",
    "randgridsagebqa2",
    "randgridsagebv",
    "randgridsagebv2",
    "rosev1",
    "rosev10",
    "rosev11",
    "rosev12",
    "rosev13",
    "rosev14",
    "rosev15",
    "rosev16",
    "rosev17",
    "rosev18",
    "rosev19",
    "rosev2",
    "rosev20",
    "rosev21",
    "rosev22",
    "rosev23",
    "rosev24",
    "rosev25",
    "rosev26",
    "rosev27",
    "rosev28",
    "rosev29",
    "rosev3",
    "rosev30",
    "rosev4",
    "rosev5",
    "rosev6",
    "rosev7",
    "rosev8",
    "rosev9",
    "rtro",
    "rtrob",
    "rtrodev",
    "rtrot",
    "s1",
    "s1t",
    "s2",
    "s2b",
    "s2c",
    "s2t",
    "s2v",
    "sagev1",
    "sagev10",
    "sagev11",
    "sagev12",
    "sagev13",
    "sagev14",
    "sagev15",
    "sagev16",
    "sagev17",
    "sagev18",
    "sagev19",
    "sagev2",
    "sagev20",
    "sagev21",
    "sagev22",
    "sagev23",
    "sagev24",
    "sagev25",
    "sagev26",
    "sagev27",
    "sagev28",
    "sagev29",
    "sagev3",
    "sagev30",
    "sagev4",
    "sagev5",
    "sagev6",
    "sagev7",
    "sagev8",
    "sagev9",
    "scor",
    "scor-beta",
    "scor-beta-dev-1",
    "scor-beta-RC",
    "scor-retail-dev-1",
    "scor-retail-rc",
    "sigrunmoonaqa",
    "sigrunmoonaqa2",
    "sigrunmoonav",
    "sigrunmoonav2",
    "sigrunmoonbqa",
    "sigrunmoonbqa2",
    "sigrunmoonbv",
    "sigrunmoonbv2",
    "sigrunpinta",
    "spot",
    "spotb",
    "spotdev",
    "spott",
    "spotv1",
    "spotv10",
    "spotv11",
    "spotv12",
    "spotv13",
    "spotv14",
    "spotv15",
    "spotv16",
    "spotv17",
    "spotv18",
    "spotv19",
    "spotv2",
    "spotv20",
    "spotv3",
    "spotv4",
    "spotv5",
    "spotv6",
    "spotv7",
    "spotv8",
    "spotv9",
    "storm",
    "viper",
    "viperdev",
    "viperv1",
    "w1r",
    "w2bn",
    "w2r",
    "w2rd",
    "w3",
    "w3b",
    "w3d",
    "w3t",
    "war1",
    "wlby",
    "wlbya",
    "wlbydev",
    "wlbyt",
    "wlbyv1",
    "wlbyv2",
    "wlbyv3",
    "wlbyv4",
    "wlbyv5",
    "wlbyv6",
    "wow",
    "wow_alpha",
    "wow_anniversary",
    "wow_beta",
    "wow_classic",
    "wow_classic_beta",
    "wow_classic_era",
    "wow_classic_era_beta",
    "wow_classic_era_ptr",
    "wow_classic_ptr",
    "wow_classic_titan",
    "wowdemo",
    "wowdev",
    "wowdev2",
    "wowdev3",
    "wowdev4",
    "wowdev5",
    "wowdev6",
    "wowe1",
    "wowe2",
    "wowe3",
    "wowlivetest",
    "wowlivetest2",
    "wowt",
    "wowv",
    "wowv10",
    "wowv2",
    "wowv3",
    "wowv4",
    "wowv5",
    "wowv6",
    "wowv7",
    "wowv8",
    "wowv9",
    "wowxptr",
    "wowz",
    "zeus",
    "zeusa",
    "zeusb",
    "zeusc",
    "zeuscdlevent",
    "zeuscdlstaff",
    "zeusdev",
    "zeusevent",
    "zeusr",
    "zeusv1",
    "zeusv10",
    "zeusv11",
    "zeusv12",
    "zeusv13",
    "zeusv14",
    "zeusv15",
    "zeusv16",
    "zeusv2",
    "zeusv3",
    "zeusv4",
    "zeusv5",
    "zeusv6",
    "zeusv7",
    "zeusv8",
    "zeusv9",
)

# Codename prefixes for well-known game titles.
# Longer prefixes are matched first to avoid ambiguity.
_CODENAME_PREFIXES = {
    "d3": "Diablo3",
    "fenris": "Diablo4",
    "hs": "Hearthstone",
    "pro": "Overwatch",
    "s1": "StarCraft",
    "s2": "StarCraft2",
    "w3": "Warcraft3",
    "wow": "Wow",
    "zeus": "CallOfDuty",
}

# Explicit enum name overrides where codename prefix + auto-generation
# doesn't produce the conventional name.
_ENUM_NAME_OVERRIDES = {
    "d3t": "Diablo3Ptr",
    "fenrisb": "Diablo4Beta",
    "hsb": "Hearthstone",
    "hsc": "HearthstoneTournament",
    "prot": "OverwatchTest",
    "zeus": "CallOfDutyBlackOpsColdWar",
    "wowlivetest": "WowLiveTest",
    "wowlivetest2": "WowLiveTest2",
    "wowxptr": "WowXPtr",
}

# CLI name overrides for well-known products.
# Maps CDN code to user-friendly kebab-case CLI name.
_CLI_NAME_OVERRIDES = {
    "d3": "diablo3",
    "d3cn": "diablo3-cn",
    "d3t": "diablo3-ptr",
    "d3vcn": "diablo3-v-cn",
    "fenris": "diablo4",
    "fenrisb": "diablo4-beta",
    "hsb": "hearthstone",
    "hsc": "hearthstone-tournament",
    "pro": "overwatch",
    "prot": "overwatch-test",
    "w3": "warcraft3",
    "zeus": "call-of-duty-black-ops-cold-war",
    "wowdemo": "wow-demo",
    "wowdev": "wow-dev",
    "wowdev2": "wow-dev2",
    "wowdev3": "wow-dev3",
    "wowdev4": "wow-dev4",
    "wowdev5": "wow-dev5",
    "wowdev6": "wow-dev6",
    "wowe1": "wow-e1",
    "wowe2": "wow-e2",
    "wowe3": "wow-e3",
    "wowlivetest": "wow-live-test",
    "wowlivetest2": "wow-live-test2",
    "wowt": "wow-t",
    "wowv": "wow-v",
    "wowv2": "wow-v2",
    "wowv3": "wow-v3",
    "wowv4": "wow-v4",
    "wowv5": "wow-v5",
    "wowv6": "wow-v6",
    "wowv7": "wow-v7",
    "wowv8": "wow-v8",
    "wowv9": "wow-v9",
    "wowv10": "wow-v10",
    "wowxptr": "wow-x-ptr",
    "wowz": "wow-z",
}

# Sorted codename prefixes (longest first) for matching
_SORTED_PREFIXES = sorted(_CODENAME_PREFIXES.items(), key=lambda x: -len(x[0]))


def _code_to_enum_name(code: str) -> str:
    """Convert a CDN product code to a PascalCase enum member name."""
    if code in _ENUM_NAME_OVERRIDES:
        return _ENUM_NAME_OVERRIDES[code]

    for prefix, game_name in _SORTED_PREFIXES:
        if code == prefix:
            return game_name
        if code.startswith(prefix):
            suffix = code[len(prefix):]
            parts = re.split(r"[_-]", suffix)
            suffix_name = "".join(p.capitalize() for p in parts if p)
            return game_name + suffix_name

    # Default: split on _ and -, capitalize each part
    parts = re.split(r"[_-]", code)
    return "".join(p.capitalize() for p in parts if p)


def _code_to_cli_name(code: str) -> str:
    """Convert a CDN product code to a kebab-case CLI name."""
    if code in _CLI_NAME_OVERRIDES:
        return _CLI_NAME_OVERRIDES[code]
    return code.replace("_", "-").lower()


# Verify no duplicate enum names at import time
_seen_names: Dict[str, str] = {}
for _code in ALL_PRODUCT_CODES:
    _name = _code_to_enum_name(_code)
    if _name in _seen_names:
        raise ValueError(
            f"Duplicate enum name '{_name}' for codes "
            f"'{_seen_names[_name]}' and '{_code}'"
        )
    _seen_names[_name] = _code
del _seen_names

Product = Enum("Product", {_code_to_enum_name(c): c for c in ALL_PRODUCT_CODES})


def _build_product_name_map() -> Dict[str, str]:
    """Build the product name map with both CDN-derived and friendly CLI names."""
    name_map: Dict[str, str] = {}
    for code in ALL_PRODUCT_CODES:
        enum_name = _code_to_enum_name(code)
        # CDN code with _ replaced by - (always valid as CLI name)
        auto_name = code.replace("_", "-").lower()
        name_map[auto_name] = enum_name
        # Friendly CLI name (if different from auto)
        if code in _CLI_NAME_OVERRIDES:
            name_map[_CLI_NAME_OVERRIDES[code]] = enum_name
    return name_map


PRODUCT_NAME_MAP: Dict[str, str] = _build_product_name_map()

# Default products for the grab command.
# All WoW, Warcraft, Overwatch, Hearthstone, and Diablo 4 product codes.
_DEFAULT_PREFIXES = ("wow", "w1", "w2", "w3", "war", "pro", "hs", "fenris", "drtl")
DEFAULT_PRODUCTS: List[str] = sorted(
    {
        _code_to_cli_name(c)
        for c in ALL_PRODUCT_CODES
        if any(c.startswith(p) for p in _DEFAULT_PREFIXES)
    }
)


def product_name_to_enum(product_name: str) -> Optional[Product]:
    """Convert product name (kebab-case or CDN code) to Product enum."""
    enum_name = PRODUCT_NAME_MAP.get(product_name.lower())
    if enum_name:
        try:
            return Product[enum_name]
        except KeyError:
            return None
    return None
